### ISSUE TITLE
BrowserOS crashing right after opening on mac

### ISSUE THREAD

**Issue by Safra1976** [browseros-ai/BrowserOS#48]
To give context, it started to happen after I uninstalled https://browseroperator.io/.

Thanks in advance!

Full report attached.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               BrowserOS [1627]
Path:                  /Applications/BrowserOS.app/Contents/MacOS/BrowserOS
Identifier:            com.browseros.BrowserOS
Version:               137.0.7189.69 (7189.69)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2025-07-30 08:37:49.1079 -0300
OS Version:            macOS 15.2 (24C101)
Report Version:        12
Anonymous UUID:        782DC206-A4A1-F65F-D9AB-38FD20ECC94B

[Untitled.txt](https://github.com/user-attachments/files/21508830/Untitled.txt)

**Comment by Ilovecatz17** [comment]
Happens to me too but i didnt uninstall anything before

[report.txt](https://github.com/user-attachments/files/21537226/report.txt)

**Comment by shadowfax92** [comment]
@Ilovecatz17 @Safra1976 we fixed this crashed in recent releases. The version you have is `0.15.0`, can you please test this in [0.18.0](https://github.com/browseros-ai/BrowserOS/releases/tag/v0.18.0). 

Thank you for reporting!

**Comment by Safra1976** [comment]
Thank you for your reply!

I installed v. 0.18 but it still crashing...

[Untitled.txt](https://github.com/user-attachments/files/21559700/Untitled.txt)

**Comment by shadowfax92** [comment]
Thank your testing with v0.18.0 and sorry it still crashes! ☹️ Weird though, I use a mac too and works fine. I'll try to reproduce this.

Thanks for the crash dump.

**Comment by Ilovecatz17** [comment]
[Untitled.txt](https://github.com/user-attachments/files/21690120/Untitled.txt)

on most recent version too

**Comment by shadowfax92** [comment]
@Safra1976 @Ilovecatz17  I’m not able to reproduce this issue on my end (tested on MacBook M4 Max and Mac Mini).

I’ve built a new binary with extra logging so we can figure out what’s going on. Could you install this debug version of BrowserOS?
[BrowserOS_0.19.0_debug_arm64.dmg](http://files.browseros.com/dmg/BrowserOS_0.19.0_debug_arm64.dmg)

Once installed, please run this command in Terminal to capture the logs:

```
/Applications/BrowserOS.app/Contents/MacOS/BrowserOS --enable-logging=stderr --v=2 > ~/browseros-$(date +%Y-%m-%d_%H-%M-%S).log 2>&1
```

Once you run that, you’ll find the log file in your home directory.  Could you please send me that file?  You can email me the log file to [support@browseros.com](mailto:support@browseros.com). That would really help. Thank you!

**Comment by mateuszjablonski** [comment]
I think I found the issue.

This is a database version conflict between different Chromium-based browsers sharing the same data directory. I had `ungoogled-chromium` installed, and it created a web app database with schema version 3, but BrowserOS expects version 2. When BrowserOS tries to read the database, it hits a fatal assertion failure at `chrome/browser/web_applications/web_app_database.cc:160` with the error `Check failed: state.metadata.version() == GetCurrentDatabaseVersion()` (3 vs. 2).

Root cause: both browsers were using **the same** ~/Library/Application Support/Chromium/ which caused the conflict.

To reproduce:
- uninstall any Chromium based browsers
- install `ungoogled-chromium` with `brew install eloston-chromium`
- install BrowserOS
- open `ungoogled-chromium`, load any page, close it
- open BrowserOS - it will crash immediately

Temporary fix is to run BrowserOS with its own user data directory:
`/Applications/BrowserOS.app/Contents/MacOS/BrowserOS --user-data-dir="~/Library/Application Support/BrowserOS"`

But I have no idea if this can be changed - I assume `ungoogled-chromium` would move to its own app support directory too.

**Comment by shadowfax92** [comment]
@mateuszjablonski oh wow, thank you for the details and repro instructions! I'll try this out. Should be fixable.

**Comment by shadowfax92** [comment]
I believe this issue should now be fixed with the [0.20.0](https://github.com/browseros-ai/BrowserOS/releases/tag/v0.20.0) release. I was able to reproduce it using the steps suggested by @mateuszjablonski and have implemented a fix!

Thank you @Ilovecatz17 @Safra1976 and @mateuszjablonski 🙌 Can you guys please try and confirm once 🙂

**Comment by shadowfax92** [comment]
Awesome! 🥳
